version: '3.8'

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    
    celery:
        build: .
        command: celery -A dockerproject worker -l info
        volumes:
            - .:/usr/src/app 
        depends_on:
            - django
            - redis
    
    celery_beat:
        build: .
        command: celery -A dockerproject beat -l info
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - redis

    migrations:
        build: .
        container_name: migrations
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
    pgdb:
        image: postgres:14.10
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: redis:7.0.14
        container_name: redis
volumes:
    pgdata: