version: '3.8'

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        environment:
            - CELERY_BROKER_URL=${redis}
            - CELERY_RESULT_BACKEND=${redis}
        depends_on:
            - pgdb
            - redis

    celery:
        build: .
        command: celery -A home worker -l info
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - redis

    celery_beat:
        build: .
        command: celery -A home beat -l info
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - redis

    flower:
        image: mher/flower
        command: celery --broker=redis://redis:6379/0 flower --port=5555
        ports:
            - 5557:5555
        depends_on:
            - redis

    migrations:
        build: .
        container_name: migrations
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
    pgdb:
        image: postgres:${pgdbv}
        container_name: pgdb
        environment:
            - POSTGRES_DB=${NAME}
            - POSTGRES_USER=${NAME}
            - POSTGRES_PASSWORD=${PASS}
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: redis:${redisv}
        container_name: redis
volumes:
    pgdata:
